<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Data Mining</b></center>
<center><b><h1>Lab - 2</b></center>
<center><b><h1>23010101282 | Sumit Vadhava | 11-06-2025 </b></center>
<pre>

# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [3]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [5]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [6]:
arr2 = np.array([10,20,30,40,50,60])
print(arr2)

[10 20 30 40 50 60]


### Step 3. Reshape 1D to 2D Array

In [8]:
arr = arr.reshape(3,2)
print(arr)

[[1 2]
 [3 4]
 [5 6]]


### Step 4. Create a Linspace array

In [10]:
linspace_arr = np.linspace(2,10,num=20,dtype=float)
print(linspace_arr)


[ 2.          2.42105263  2.84210526  3.26315789  3.68421053  4.10526316
  4.52631579  4.94736842  5.36842105  5.78947368  6.21052632  6.63157895
  7.05263158  7.47368421  7.89473684  8.31578947  8.73684211  9.15789474
  9.57894737 10.        ]


### Step 5. Create a Random Numbered Array

In [14]:
random_arr = np.random.rand(3,2)
print(random_arr)

[[0.99592714 0.92263371]
 [0.74674006 0.9089027 ]
 [0.99606429 0.20653027]]


### Step 6. Create a Random Integer Array

In [19]:
random_int_arr = np.random.randint(1,10,(2,5))

In [20]:
print(random_int_arr)

[[1 7 1 4 7]
 [2 4 8 6 7]]


### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [21]:
random_int_arr = np.random.randint(1,10,(1,10))

In [22]:
print(random_int_arr)

[[8 8 3 4 3 3 7 9 7 6]]


In [28]:
max = random_int_arr.max()
print("Max:",max)

Max: 9


In [29]:
min = random_int_arr.min()
print("Min:",min)

Min: 3


In [32]:
arg_min = random_int_arr.argmin()
print("arg_min(Index of min):",arg_min)

arg_min(Index of min): 2


In [31]:
arg_max = random_int_arr.argmax()
print("arg_max(Index of max):",arg_max)

arg_max(Index of max): 7


### Step 8. Indexing in 1D Array

In [33]:
arr = np.array([10,20,30,40])

In [38]:
print("Number at index 2 :",arr[2])
print("Number at index 3:",arr[3])
print("The last element of thw arr :",arr[-1])

Number at index 2 : 30
Number at index 3: 40
The last element of thw arr : 40


In [42]:
print(arr[1:])
print(arr[0:3])
print(arr[::2])


[20 30 40]
[10 20 30]
[10 30]


### Step 9. Indexing in 2D Array

In [43]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print("Number at the second row and second column :",arr[1][1])

Number at the first row and first column : 5


In [48]:
print("Number at the third row and first column :",arr[2][0])

Number at the third row and first column : 7


In [56]:
print(arr[1:3,1:])
print("----------------")
print(arr[2:3,1:2])


[[5 6]
 [8 9]]
----------------
[[8]]


### Step 10. Conditional Selection

In [59]:
print("The numbers in array greater then 5:",arr[arr>5])

The numbers in array greater then 5: [ 6  7  8  9 10 11 12]


In [60]:
print("The even numbers in the array:",arr[arr%2 == 0])

The even numbers in the array: [ 2  4  6  8 10 12]


### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [61]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [82]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'

users = pd.read_csv(url, sep='|',index_col='user_id')
users

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries

In [83]:
users.head(25)

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [84]:
users.tail(10)

age gender     occupation zip_code
user_id                                    
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [86]:
len(users)

943

### Step 7. What is the number of columns in the dataset?

In [87]:
len(users.columns)

4

### Step 8. Print the name of all the columns.

In [88]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [89]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [90]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [ ]:
users['occupation']
users.occupation #this is also work

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [97]:
users.occupation.unique().size

21

### Step 13. What is the most frequent occupation?

In [114]:
occupation_counts = users.groupby('occupation').size()

max_count = occupation_counts.max()

most_common = occupation_counts[occupation_counts == max_count]

print(most_common)


occupation
student    196
dtype: int64


In [133]:
occupation_counts = users['occupation'].value_counts()

max_count = occupation_counts.max()

most_common_occupations = occupation_counts[occupation_counts == max_count]

print(most_common_occupations)


occupation
student    196
Name: count, dtype: int64


### Step 14. Summarize the DataFrame.

In [115]:
users.describe()

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [116]:
users.describe(include='all')

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [118]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [119]:
print(users['age'].mean())

34.05196182396607


### Step 18. What is the age with least occurrence?

In [134]:
grouped_ages_sizes = users.groupby(['age']).size()

min_count = grouped_ages_sizes.min()

least_occur = grouped_ages_sizes[grouped_ages_sizes == min_count]
print(least_occur)


age
7     1
10    1
11    1
66    1
73    1
dtype: int64


In [ ]:
grouped_ages_sizes = users['age'].value_counts()

min_count =  grouped_ages_sizes.min()
    
least_occur = grouped_ages_sizes[grouped_ages_sizes == min_count]
print(least_occur)


age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64


### You're not just learning, you're mastering it. Keep aiming higher! 🚀